"""Service for Gemini-powered diff-aware test plan generation with content-addressed caching."""
import hashlib
import json
import logging
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Optional

try:
    from google import genai
    from google.genai import types
except ImportError:
    genai = None
    types = None

try:
    import httpx
except ImportError:
    httpx = None

from automation.domain.test_plan import (
    ActionType,
    AssertionType,
    DiffAnalysisResult,
    TestAction,
    TestAssertion,
    TestJourney,
    TestPlan,
)
from automation.interfaces.diff_test_generator_interface import IDiffTestGeneratorService
from automation.interfaces.test_plan_engine_interface import ITestPlanEngine

logger = logging.getLogger(__name__)

# Maximum diff size to send to Gemini (prevents context overflow)
# About 50k tokens: room for a feature-sized diff (a new page and its routes) within the
# model's context. At 8000, a plan was written from the first files only and guessed the rest.
MAX_DIFF_CHARS = 200_000

# Maximum journeys per test plan (prevents overly complex test plans)
MAX_JOURNEYS = 5

# Maximum cached test plans to keep; the oldest are pruned after each write
MAX_CACHE_ENTRIES = 50

# Bump whenever the system prompt or response schema changes, so that cached
# plans generated by an older prompt are not reused.
PROMPT_VERSION = "4"

# Gemini answers 503 "high demand" and 429 in bursts that usually clear within a
# minute. Without a retry, one such reply turned a feature's QA run into a smoke
# test of the homepage.
RETRYABLE_STATUS_CODES = frozenset({429, 500, 502, 503, 504})
RETRY_DELAYS_SECONDS = (5, 15, 40)

# Connection resets, DNS failures and timeouts carry no HTTP status, and clear just as fast.
TRANSIENT_ERROR_TYPES = (ConnectionError, TimeoutError) + ((httpx.TransportError,) if httpx else ())

GEMINI_SYSTEM_PROMPT = """You are a QA test plan generator. You analyze git diffs to identify user-facing UI changes
and produce structured test plans.

Your task:
1. Analyze the provided git diff to identify UI-facing changes (components, pages, routes, forms, buttons, labels, etc.).
2. If there are NO UI-facing changes (e.g., only backend logic, config, documentation), respond with has_ui_changes=false.
3. If there ARE UI-facing changes, generate test journeys that verify the user-visible impact.

Rules for test journeys:
- Each journey targets ONE specific user flow affected by the diff.
- Use accessible selectors: role-based (button, link, textbox, heading) and visible text. NEVER use CSS selectors or test IDs.
- Every click, fill and select target MUST be text copied verbatim from the diff, never a description of the element
  (write "Admin Panel", not "link to Admin"; write "Search posts...", not "textbox for search"):
  - click: the button or link text, or its aria-label or title.
  - fill: the field's label text, aria-label, or placeholder.
  - select: the dropdown's label or aria-label; for a dropdown with neither, the text of one of its options.
- A select value MUST be an option text written in the diff. Options rendered from fetched data are
  unknown, so choose a static option (such as "All Categories") or leave the select out.
- entry_route and navigate targets MUST be routes from "Declared routes" in the context, or routes the
  diff adds. Never invent one (no "/home" unless it is declared). Reach a route with a parameter
  (such as "/posts/:id") by clicking, not by navigating. Without declared routes, start from "/".
- Actions should be realistic user interactions: navigate, click, fill, scroll, select, wait.
- fill and select actions MUST include a value.
- wait actions set target to the visible text to wait for, optionally with duration_ms as its timeout,
  or leave target empty and set duration_ms for a fixed wait.
- Assertions should verify VISIBLE outcomes: text appears, elements exist, alerts show, state updates.
- Keep journeys focused and concise (3-8 actions each).
- Maximum 5 journeys per plan.
"""

GEMINI_TEST_PLAN_SCHEMA = {
    "type": "object",
    "properties": {
        "has_ui_changes": {"type": "boolean"},
        "summary": {"type": "string"},
        "modified_components": {"type": "array", "items": {"type": "string"}},
        "modified_routes": {"type": "array", "items": {"type": "string"}},
        "journeys": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "entry_route": {"type": "string"},
                    "actions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "action_type": {
                                    "type": "string",
                                    "enum": ["navigate", "click", "fill", "scroll", "select", "wait"],
                                },
                                "target": {"type": "string"},
                                "value": {"type": "string"},
                                "duration_ms": {"type": "integer"},
                                "description": {"type": "string"},
                            },
                            "required": ["action_type", "target", "description"],
                        },
                    },
                    "assertions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "enum": ["visible_text", "element_exists", "alert_message", "state_update"],
                                },
                                "target": {"type": "string"},
                                "description": {"type": "string"},
                            },
                            "required": ["type", "target", "description"],
                        },
                    },
                },
                "required": ["name", "entry_route", "actions", "assertions"],
            },
        },
    },
    "required": ["has_ui_changes", "summary"],
}


class GeminiDiffTestGeneratorService(IDiffTestGeneratorService):
    """Generates test plans from git diffs using Gemini Flash for semantic analysis.

    Features:
    - An optional primary engine (agy on the Pro plan login) tried before the Gemini API
    - Commit-SHA determinism caching to avoid redundant LLM calls on re-runs
    - Automatic fallback to baseline smoke tests when no UI changes detected or on error
    - Structured JSON output enforced via response_schema
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        gemini_model: Optional[str] = None,
        genai_client: Optional[Any] = None,
        sleep: Callable[[float], None] = time.sleep,
        primary_engine: Optional[ITestPlanEngine] = None,
    ) -> None:
        from automation.core.credentials import get_gemini_api_key, normalize_gemini_model

        self._api_key = api_key if api_key is not None else get_gemini_api_key()
        self._model_name = normalize_gemini_model(gemini_model)
        self._genai_client = genai_client
        self._sleep = sleep
        self._primary_engine = primary_engine

    def _get_client(self) -> Any:
        """Returns the Gemini client, creating one lazily if needed."""
        if self._genai_client is not None:
            return self._genai_client

        if genai is None:
            raise RuntimeError(
                "google-genai package is not installed. "
                "Install it with: pip install google-genai"
            )

        if not self._api_key:
            raise ValueError(
                "Gemini API key is required for test plan generation. "
                "Set AGY_API_KEY, GEMINI_API_KEY, or ANTIGRAVITY_API_KEY environment variable."
            )

        self._genai_client = genai.Client(api_key=self._api_key)
        return self._genai_client

    def _build_baseline_fallback(
        self, commit_sha: str, reason: str = "", degraded: bool = False
    ) -> TestPlan:
        """Builds a minimal baseline smoke test plan as a fallback.

        This ensures the pipeline always has at least one test to execute,
        even when Gemini is unavailable or the diff has no UI changes.

        Args:
            commit_sha: Commit the plan is generated for.
            reason: Why the fallback was used.
            degraded: True when the cause was an error rather than the diff's
                content. Degraded plans are not cached, so a transient API
                failure cannot pin a smoke test to these changes.
        """
        logger.info(f"Using fallback baseline smoke test. Reason: {reason or 'No UI changes detected'}")
        return TestPlan(
            commit_sha=commit_sha,
            generated_at=datetime.now(timezone.utc),
            source="fallback_baseline",
            raw_diff_summary=reason or "No UI-facing changes detected; running baseline smoke test.",
            degraded=degraded,
            journeys=[
                TestJourney(
                    name="Baseline smoke test - verify application loads",
                    entry_route="/",
                    actions=[
                        TestAction(
                            action_type=ActionType.NAVIGATE,
                            target="/",
                            description="Navigate to the application root",
                        ),
                        TestAction(
                            action_type=ActionType.WAIT,
                            target="",
                            duration_ms=2000,
                            description="Wait for application to fully render",
                        ),
                    ],
                    assertions=[
                        TestAssertion(
                            type=AssertionType.CSS_SELECTOR,
                            target="body",
                            description="Verify the page body is rendered",
                        ),
                    ],
                ),
            ],
        )

    @staticmethod
    def _is_retryable(error: Exception) -> bool:
        """True for errors a later attempt can succeed past: overload, rate limit, server fault, network."""
        if getattr(error, "code", None) in RETRYABLE_STATUS_CODES:
            return True
        return isinstance(error, TRANSIENT_ERROR_TYPES)

    def _generate_with_retry(self, client: Any, user_prompt: str) -> Any:
        """Call Gemini, retrying transient failures with backoff before giving up."""
        for attempt, delay in enumerate((*RETRY_DELAYS_SECONDS, None), start=1):
            try:
                return client.models.generate_content(
                    model=self._model_name,
                    contents=user_prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=GEMINI_SYSTEM_PROMPT,
                        response_mime_type="application/json",
                        response_schema=GEMINI_TEST_PLAN_SCHEMA,
                        temperature=0.2,
                    ),
                )
            except Exception as e:
                if delay is None or not self._is_retryable(e):
                    raise
                logger.warning(f"Gemini attempt {attempt} failed ({e}); retrying in {delay}s...")
                self._sleep(delay)

    def _truncate_diff(self, diff: str) -> str:
        """Truncates large diffs to fit Gemini context limits.

        Preserves file path headers and function signatures while trimming
        large inline content blocks.
        """
        if len(diff) <= MAX_DIFF_CHARS:
            return diff

        logger.warning(
            f"Diff exceeds {MAX_DIFF_CHARS} chars ({len(diff)} chars). "
            f"Truncating to prevent Gemini context overflow."
        )

        def is_priority(line: str) -> bool:
            # File path headers and hunk markers
            return (
                line.startswith("diff --git")
                or line.startswith("---")
                or line.startswith("+++")
                or line.startswith("@@")
            )

        marker = "... [diff truncated for context limit] ..."
        budget = MAX_DIFF_CHARS - len(marker) - 1  # Reserve room for the marker line
        lines = diff.splitlines()

        # Reserve room for every header first, so headers of later files survive
        # even after earlier files' content has used up its share.
        priority_chars = sum(len(line) + 1 for line in lines if is_priority(line))
        content_budget = max(budget - priority_chars, 0)

        truncated_lines: list[str] = []
        total_chars = 0
        content_chars = 0
        content_exhausted = False

        for line in lines:
            line_len = len(line) + 1  # +1 for newline
            if is_priority(line):
                if total_chars + line_len > budget:
                    break
            else:
                if content_exhausted or content_chars + line_len > content_budget:
                    content_exhausted = True
                    continue
                content_chars += line_len

            truncated_lines.append(line)
            total_chars += line_len

        truncated_lines.append(marker)
        return "\n".join(truncated_lines)

    def _parse_gemini_response(self, raw_json: dict, commit_sha: str, source: str = "gemini") -> TestPlan:
        """Parses a model's structured JSON response into a TestPlan."""
        has_ui_changes = raw_json.get("has_ui_changes", False)
        summary = raw_json.get("summary", "")

        if not has_ui_changes:
            return self._build_baseline_fallback(
                commit_sha, reason=f"Gemini analysis: {summary}"
            )

        raw_journeys = raw_json.get("journeys", [])
        if not raw_journeys:
            return self._build_baseline_fallback(
                commit_sha,
                reason="Gemini detected UI changes but generated no test journeys.",
                degraded=True,
            )

        # Cap the number of journeys
        journeys: list[TestJourney] = []
        for raw_j in raw_journeys[:MAX_JOURNEYS]:
            actions = []
            for raw_a in raw_j.get("actions", []):
                try:
                    actions.append(
                        TestAction(
                            action_type=ActionType(raw_a["action_type"]),
                            target=raw_a["target"],
                            value=raw_a.get("value"),
                            duration_ms=raw_a.get("duration_ms"),
                            description=raw_a.get("description", ""),
                        )
                    )
                except (KeyError, ValueError) as e:
                    logger.warning(f"Skipping malformed action in Gemini response: {e}")
                    continue

            assertions = []
            for raw_as in raw_j.get("assertions", []):
                try:
                    assertions.append(
                        TestAssertion(
                            type=AssertionType(raw_as["type"]),
                            target=raw_as["target"],
                            description=raw_as.get("description", ""),
                        )
                    )
                except (KeyError, ValueError) as e:
                    logger.warning(f"Skipping malformed assertion in Gemini response: {e}")
                    continue

            if actions or assertions:
                journeys.append(
                    TestJourney(
                        name=raw_j.get("name", f"Journey {len(journeys) + 1}"),
                        entry_route=raw_j.get("entry_route", "/"),
                        actions=actions,
                        assertions=assertions,
                    )
                )

        if not journeys:
            return self._build_baseline_fallback(
                commit_sha,
                reason="All Gemini-generated journeys had malformed actions/assertions.",
                degraded=True,
            )

        return TestPlan(
            commit_sha=commit_sha,
            generated_at=datetime.now(timezone.utc),
            source=source,
            raw_diff_summary=summary,
            journeys=journeys,
        )

    def generate_test_plan(
        self,
        diff: str,
        commit_sha: str,
        component_context: str = "",
    ) -> TestPlan:
        """Analyze a git diff and generate a structured test plan.

        The primary engine (agy), when available, is tried first; the Gemini API is used
        when it is absent or fails. Falls back to baseline smoke tests if:
        - The diff contains no UI-facing changes
        - Every engine fails
        - The response is invalid/unparseable
        """
        if not diff or not diff.strip():
            return self._build_baseline_fallback(commit_sha, reason="Empty diff provided.")

        primary_plan = self._generate_with_primary_engine(diff, commit_sha, component_context)
        if primary_plan is not None:
            return primary_plan

        return self._generate_with_api(diff, commit_sha, component_context)

    def _generate_with_primary_engine(
        self, diff: str, commit_sha: str, component_context: str
    ) -> Optional[TestPlan]:
        """Returns the primary engine's plan, or None to fall through to the Gemini API."""
        engine = self._primary_engine
        if engine is None:
            return None
        if not engine.is_available():
            logger.info(f"{engine.name} is not available; using the Gemini API for the test plan.")
            return None

        try:
            raw_json = engine.generate_plan_json(
                GEMINI_SYSTEM_PROMPT, diff, component_context, GEMINI_TEST_PLAN_SCHEMA
            )
        except Exception as e:
            logger.warning(f"{engine.name} could not write the test plan ({e}); falling back to the Gemini API.")
            return None

        plan = self._parse_gemini_response(raw_json, commit_sha, source=engine.name)
        if plan.degraded:
            logger.warning(
                f"{engine.name}'s plan was unusable ({plan.raw_diff_summary}); falling back to the Gemini API."
            )
            return None

        logger.info(f"{engine.name} wrote the test plan: {len(plan.journeys)} journey(s).")
        return plan

    def _generate_with_api(self, diff: str, commit_sha: str, component_context: str) -> TestPlan:
        """Generate the plan with the Gemini API, falling back to the baseline on failure."""
        truncated_diff = self._truncate_diff(diff)

        user_prompt = f"Analyze the following git diff and generate a test plan:\n\n```diff\n{truncated_diff}\n```"
        if component_context:
            user_prompt += f"\n\nAdditional component context:\n{component_context}"

        try:
            client = self._get_client()

            logger.info(
                f"Sending diff ({len(truncated_diff)} chars) to Gemini ({self._model_name}) "
                f"for test plan generation..."
            )

            response = self._generate_with_retry(client, user_prompt)

            raw_text = response.text
            if not raw_text:
                return self._build_baseline_fallback(
                    commit_sha, reason="Gemini returned empty response.", degraded=True
                )

            raw_json = json.loads(raw_text)
            logger.info(
                f"Gemini analysis complete. UI changes: {raw_json.get('has_ui_changes', 'unknown')}, "
                f"Journeys: {len(raw_json.get('journeys', []))}"
            )

            return self._parse_gemini_response(raw_json, commit_sha)

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse Gemini JSON response: {e}")
            return self._build_baseline_fallback(
                commit_sha, reason=f"Gemini response was not valid JSON: {e}", degraded=True
            )
        except Exception as e:
            logger.error(f"Gemini test plan generation failed: {e}")
            return self._build_baseline_fallback(
                commit_sha, reason=f"Gemini API error: {e}", degraded=True
            )

    def cache_key(self, diff: str, component_context: str = "") -> str:
        """Derive the cache key from everything the generated plan depends on.

        Keying on the diff rather than the commit SHA means a moved base branch
        (which changes the diff but not HEAD) misses, while an amend or rebase
        that leaves the content unchanged still hits.
        """
        engine = self._primary_engine.cache_identity if self._primary_engine else ""
        material = "\0".join([PROMPT_VERSION, engine, self._model_name, diff, component_context])
        return hashlib.sha256(material.encode("utf-8")).hexdigest()[:32]

    def load_cached_plan(self, cache_key: str, cache_dir: str) -> Optional[TestPlan]:
        """Load a previously generated test plan from the file cache.

        Cache files are stored as `{cache_dir}/{cache_key}.json`.
        """
        cache_path = Path(cache_dir) / f"{cache_key}.json"
        if not cache_path.is_file():
            logger.debug(f"No cached test plan found for key {cache_key[:8]}.")
            return None

        try:
            raw = cache_path.read_text(encoding="utf-8")
            plan = TestPlan.model_validate_json(raw)
            logger.info(
                f"Loaded cached test plan for key {cache_key[:8]} "
                f"(source={plan.source}, {len(plan.journeys)} journeys, commit {plan.commit_sha[:8]})."
            )
            return plan
        except Exception as e:
            logger.warning(f"Failed to load cached test plan for key {cache_key[:8]}: {e}")
            return None

    def save_cached_plan(self, plan: TestPlan, cache_key: str, cache_dir: str) -> None:
        """Persist a generated test plan to the cache directory.

        Creates the cache directory if it does not exist, then prunes the oldest
        entries so the cache cannot grow without bound.
        """
        cache_path = Path(cache_dir)
        cache_path.mkdir(parents=True, exist_ok=True)

        output_file = cache_path / f"{cache_key}.json"
        try:
            output_file.write_text(
                plan.model_dump_json(indent=2),
                encoding="utf-8",
            )
            logger.info(f"Cached test plan for key {cache_key[:8]} -> {output_file}")
        except Exception as e:
            logger.warning(f"Failed to cache test plan for key {cache_key[:8]}: {e}")
            return

        self._prune_cache(cache_path)

    def _prune_cache(self, cache_path: Path) -> None:
        """Delete the oldest cache entries beyond MAX_CACHE_ENTRIES."""
        try:
            entries = sorted(
                cache_path.glob("*.json"),
                key=lambda p: p.stat().st_mtime,
                reverse=True,
            )
        except OSError as e:
            logger.debug(f"Could not list cache directory for pruning: {e}")
            return

        for stale in entries[MAX_CACHE_ENTRIES:]:
            try:
                stale.unlink()
                logger.debug(f"Pruned stale cached test plan: {stale.name}")
            except OSError:
                # A concurrent run may have removed it already
                pass
