import os
import re
import subprocess
from typing import Optional

from automation.domain.models import GitPRDetails, WorkflowEnvironment
from automation.interfaces.metadata_service_interface import IMetadataService

try:
    from google import genai
    from google.genai import types
    HAS_GENAI_SDK = True
except ImportError:
    HAS_GENAI_SDK = False

class GeminiLLMMetadataService(IMetadataService):
    """Concrete implementation of IMetadataService utilizing official google-genai SDK."""
    
    def __init__(self, config: WorkflowEnvironment):
        self.config = config

    def _get_git_diff_summary(self) -> str:
        res = subprocess.run(["git", "diff", "--stat"], capture_output=True, text=True)
        return res.stdout.strip()[:1000]

    def generate_metadata(self) -> GitPRDetails:
        api_key = os.getenv("AGY_API_KEY") or os.getenv("GEMINI_API_KEY") or os.getenv("ANTIGRAVITY_API_KEY", "").strip()
        diff_summary = self._get_git_diff_summary()
        
        # 1. Use Google's Official SDK if available and API key present
        if HAS_GENAI_SDK and api_key:
            try:
                client = genai.Client(api_key=api_key)
                
                system_instruction = (
                    "You are an expert Git Release Manager.\n"
                    "Your task: Generate semantic Git metadata for a Pull Request based on the user's prompt and git diff summary.\n"
                    "Follow Conventional Commit standard for commit_message and pr_title.\n"
                    "Format branch_name as a short kebab-case string starting with feat/, fix/, or refactor/."
                )

                prompt_content = f"User Prompt: {self.config.user_prompt}\nGit Diff Summary:\n{diff_summary}"

                response = client.models.generate_content(
                    model=self.config.model_name,
                    contents=prompt_content,
                    config=types.GenerateContentConfig(
                        system_instruction=system_instruction,
                        response_mime_type="application/json",
                        response_schema=GitPRDetails
                    )
                )

                if response.parsed and isinstance(response.parsed, GitPRDetails):
                    details: GitPRDetails = response.parsed
                    print(f"🤖 google-genai SDK Generated Branch Name: {details.branch_name}")
                    print(f"🤖 google-genai SDK Generated Commit Title: {details.commit_message}")
                    return details
            except Exception as e:
                print(f"⚠️ google-genai SDK call exception: {e}. Falling back to default formatting.")

        # 2. Failsafe fallback logic if SDK is missing or key is absent
        clean_slug = re.sub(r"[^a-z0-9]", "-", self.config.user_prompt.lower())
        clean_slug = re.sub(r"-+", "-", clean_slug).strip("-")[:35]
        timestamp = int(subprocess.check_output(["date", "+%s"]).decode().strip())
        branch_name = f"feat/{clean_slug}-{timestamp}"
        commit_msg = f"🤖 Antigravity AI Patch ({self.config.model_name}): {self.config.user_prompt}"

        return GitPRDetails(
            branch_name=branch_name,
            commit_message=commit_msg,
            pr_title=commit_msg,
            pr_body=f"Automated PR generated by Google Antigravity Agent Engine for: {self.config.user_prompt}"
        )
