import os
import re
import json
import urllib.request
import subprocess
from typing import Optional
from automation.domain.models import GitPRDetails, WorkflowEnvironment

class LLMMetadataService:
    """Service responsible for using LLM (Gemini) to generate semantic branch names, conventional commits, and rich PR descriptions."""
    
    def __init__(self, config: WorkflowEnvironment):
        self.config = config

    def _get_git_diff_summary(self) -> str:
        res = subprocess.run(["git", "diff", "--stat"], capture_output=True, text=True)
        return res.stdout.strip()[:1000]

    def generate_metadata(self) -> GitPRDetails:
        api_key = os.getenv("AGY_API_KEY") or os.getenv("GEMINI_API_KEY") or os.getenv("ANTIGRAVITY_API_KEY", "").strip()
        diff_summary = self._get_git_diff_summary()
        
        # If API key is available, use Gemini LLM for structured semantic metadata generation
        if api_key:
            try:
                url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.config.model_name}:generateContent?key={api_key}"
                
                system_instruction = (
                    "You are an expert Git Release Manager.\n"
                    "Your task: Generate semantic Git metadata for a Pull Request based on the user's prompt and git diff summary.\n"
                    "Output JSON matching this exact schema:\n"
                    "{\n"
                    '  "branch_name": "feat/short-kebab-case-description",\n'
                    '  "commit_message": "type(scope): concise description",\n'
                    '  "pr_title": "type(scope): concise description",\n'
                    '  "pr_body": "Detailed markdown description of changes..."\n'
                    "}"
                )

                prompt_content = f"User Prompt: {self.config.user_prompt}\nGit Diff Summary:\n{diff_summary}"

                payload = {
                    "contents": [{
                        "role": "user",
                        "parts": [{"text": f"{system_instruction}\n\n{prompt_content}"}]
                    }],
                    "generationConfig": {
                        "response_mime_type": "application/json"
                    }
                }

                req = urllib.request.Request(
                    url,
                    data=json.dumps(payload).encode("utf-8"),
                    headers={"Content-Type": "application/json"}
                )

                with urllib.request.urlopen(req, timeout=10) as resp:
                    res_data = json.loads(resp.read().decode("utf-8"))
                    text = res_data["candidates"][0]["content"]["parts"][0]["text"]
                    parsed = json.loads(text)

                    raw_branch = parsed.get("branch_name", "feat/ai-patch")
                    clean_branch = re.sub(r"[^a-zA-Z0-9_.-]", "-", raw_branch.lower())
                    if not clean_branch.startswith("feat/") and not clean_branch.startswith("fix/") and not clean_branch.startswith("refactor/"):
                        clean_branch = f"feat/{clean_branch}"

                    print(f"🤖 LLM Generated Branch Name: {clean_branch}")
                    print(f"🤖 LLM Generated Commit Title: {parsed.get('commit_message')}")

                    return GitPRDetails(
                        branch_name=clean_branch,
                        commit_message=parsed.get("commit_message", f"feat: {self.config.user_prompt}"),
                        pr_title=parsed.get("pr_title", f"feat: {self.config.user_prompt}"),
                        pr_body=parsed.get("pr_body", f"Automated PR for: {self.config.user_prompt}")
                    )
            except Exception as e:
                print(f"⚠️ LLM metadata generation failed or timed out: {e}. Falling back to default formatting.")

        # Failsafe fallback logic if no LLM key or offline
        clean_slug = re.sub(r"[^a-z0-9]", "-", self.config.user_prompt.lower())
        clean_slug = re.sub(r"-+", "-", clean_slug).strip("-")[:35]
        timestamp = int(subprocess.check_output(["date", "+%s"]).decode().strip())
        branch_name = f"feat/{clean_slug}-{timestamp}"
        commit_msg = f"🤖 Antigravity AI Patch ({self.config.model_name}): {self.config.user_prompt}"

        return GitPRDetails(
            branch_name=branch_name,
            commit_message=commit_msg,
            pr_title=commit_msg,
            pr_body=f"Automated PR generated by Google Antigravity Agent Engine for: {self.config.user_prompt}"
        )
