import os
import re
import subprocess
from automation.domain.models import GitPRDetails

class LogParserService:
    """Service responsible for extracting SUGGESTED_BRANCH & SUGGESTED_COMMIT tags from agy logs."""
    
    def __init__(self, log_path: str, prompt: str, model_name: str, effort_val: str):
        self.log_path = log_path
        self.prompt = prompt
        self.model_name = model_name
        self.effort_val = effort_val

    def parse_details(self) -> GitPRDetails:
        suggested_branch = None
        suggested_commit = None
        
        if os.path.exists(self.log_path):
            with open(self.log_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
                
                branch_matches = re.findall(r"SUGGESTED_BRANCH:\s*([^\n\r]+)", content)
                if branch_matches:
                    raw_branch = branch_matches[-1].strip()
                    suggested_branch = re.sub(r"[^a-zA-Z0-9_.-]", "-", raw_branch.lower())
                
                commit_matches = re.findall(r"SUGGESTED_COMMIT:\s*([^\n\r]+)", content)
                if commit_matches:
                    suggested_commit = commit_matches[-1].strip()

        # Failsafe fallback logic if agy did not output custom tags
        if not suggested_branch:
            clean_slug = re.sub(r"[^a-z0-9]", "-", self.prompt.lower())
            clean_slug = re.sub(r"-+", "-", clean_slug).strip("-")[:35]
            timestamp = int(subprocess.check_output(["date", "+%s"]).decode().strip())
            suggested_branch = f"feat/{clean_slug}-{timestamp}"

        if not suggested_commit:
            suggested_commit = f"🤖 Antigravity AI Patch ({self.model_name}): {self.prompt}"

        pr_title = suggested_commit
        pr_body = (
            f"Automated PR generated by Google Antigravity Agent Engine.\n\n"
            f"Model: `{self.model_name}`\n"
            f"Reasoning Effort: `{self.effort_val}`\n"
            f"Prompt: {self.prompt}\n\n"
            f"👀 Please review and merge when ready!"
        )

        return GitPRDetails(
            branch_name=suggested_branch,
            commit_message=suggested_commit,
            pr_title=pr_title,
            pr_body=pr_body
        )
