name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish Python 🐍 distribution 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup uv & Python
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Build Source and Wheel Distributions
        run: uv build

      - name: Publish Distribution to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv publish
